### ISSUE TITLE
Why use bright contrasting color for autistic spectrum users?

### ISSUE THREAD

**Issue by edouard-lopez** [UKHomeOffice/posters#29]
I just printed your PDF and wonder aboute the _"bright contrasting color for autistic spectrum users_" statement.

Could you provide some insight/links about the cognitive mechanism at stake ?

**Comment by karypun** [comment]
Hi @edouard-lopez 
Thanks for your question. Some people with autism often detect things like colours and sounds with higher intensity. They are more sensitive to their surroundings so the world appears extraordinarily sharp to them. In order to avoid this strong stimulation, it is important to opt for subdued, soft colours which would be more calming and create less arousal than bright vivid colours.

This may not be universal for everyone on the spectrum but it's generally a good thing to keep in mind and to test with users. This page has a brief overview of autism and its effects with some additional links on the bottom worth checking out: https://www.carautismroadmap.org/autism-friendly-design-ideas/
