### ISSUE TITLE
Do I have to translate both PDF and SVG files?

### ISSUE THREAD

**Issue by pkoutsod** [UKHomeOffice/posters#38]
Hi there!
Great posters and I want to help with the translation of them in **Greek**.
I only have one question: Do I have to translate the SVG files as well? And if yes, what tool do you suggest for that? A web/text editor or a software like [Inkscape](https://inkscape.org/en/develop/about-svg/)?
Best, Panos

**Comment by ei8fdb** [comment]
Hi @pkoutsod 

No you don't need to translate the SVGs, they were just provided as an open source file format so that people could use whatever application they wanted.

When we asked people what was the best file format to provide the posters in (#13) the most common was SVG.

Hence we provided them in SVG! Hope that helps. If you have any other questions, just open an issue. Thanks.
