### ISSUE TITLE
Feature request: Compile all posters into a single PDF

### ISSUE THREAD

**Issue by jguffey** [UKHomeOffice/posters#52]
to make it easier to share one cohesive package.

**Comment by robertmain** [comment]
I'm gonna chip in here and maybe suggest using LaTeX or similar to generate the posters and keeping _that_ under Git version control. I feel like using Git for binary file storage is possibly not the best idea.

**Comment by karypun** [comment]
@robertmain @jguffey We'll investigate this. Thank you.

**Comment by robertmain** [comment]
Its just because git can't diff binary fines very well so you end up with separate copies rather than a delta :)

**Comment by Ryuno-Ki** [comment]
According to its meta data the PDFs are created with InDesign right now …

**Comment by robertmain** [comment]
@Ryuno-Ki yeah - that kinda defeats the point of Git

**Comment by joelanman** [comment]
@robertmain I dont think diffs are the only point of Git :) there are still lots of advantages of using GitHub - people can easily collaborate, raise issues etc. While LaTeX might have some advantages with diffs, fewer people can actually use it, whereas design tools are more widely used.

**Comment by robertmain** [comment]
They aren't, but using git for binary files means that you are likely to
get corrupted files if you start trying to do merges and patches.

Therefore, I feel that LaTeX would be the better way to go here. It also
means that you can see what changed between versions. I get that LaTeX is
possibly less accessible to people who want to contribute, but then it's on
them to learn the language. That's like me saying that the kernel should be
written in JavaScript so that I can contribute because I don't know C.

**Comment by Ryuno-Ki** [comment]
Maybe you would be [better of with Subversion](https://stackoverflow.com/a/3368422) then …

**Comment by robertmain** [comment]
Yeah, quite possibly (I had a read of that article - that's really cool
btw). The only problem is that there's no such thing as SvnHub... Or if
there is, it's not nearly as popular github. The most sensible solution (to
me) would be to produce the posters using something like LaTeX (hell - even
HTML and CSS if you want) and then compile it to PDF. This also had the
advantage that you can use an automated build system to compile and deploy
it to production for you, not to mention lining and spell checking. You
could also probably compile to something other than PDF like word doc or
HTML in future if you feel like it (feel free to fact check that one, I'm
not handy enough with LaTeX to day that with confidence). Plus, LaTeX costs
a lot less than Adobe creative suite.

**Comment by Ryuno-Ki** [comment]
[Pandoc](http://pandoc.org/)

I can understand you point, but I assume, you are thinking to much from the PoV of a developer. Designers think differently. More UI-driven. There are some solutions for creating PDFs out of HTML files. @karypun would that be a way to explore?

**Comment by robertmain** [comment]
OK, so use Pandoc and HTML then. Whatever - it just doesn't make any sense for @UKHomeOffice to continue to use Git/GitHub to store binary PDFs like this. Not only is it horribly inefficient, but it means that anyone who might want to contribute has to purchase Adobe Creative Suite (not all of us are made of money ;) )

**Comment by karypun** [comment]
@Ryuno-Ki @robertmain we are building the posters in HTML at the moment. Please bear with us.  These were initially internal posters we created within the team and didn't realise the interest it generated when we shared them on GitHub. This has been a learning process for us and we have been taking on board suggestions where we can. Regarding software, because we initially created them in Sketch (not everyone has Sketch and it's Mac-based) we produced alternate SVG versions for people to use as it was a better format for many types of software, Adobe CS or not. 
But as @joelanman says, GitHub is a great way for sharing and feeding back on things in order to improve and to have these kind of discussions. Like I said earlier, there's a few of us coding them and I'll report when they're ready :)

**Comment by karypun** [comment]
Thanks for the comments everyone. Having reviewed LaTeX the team have decided to continue with our current distribution method. LaTeX poses many benefits however the design team has no experience in this and as such it makes contributing too difficult. I’m going to close this issue now thanks.

**Comment by robertmain** [comment]
Cool - are you planning to swap out the PDFs from here and replace them with the HTML for contributors?

**Comment by joelanman** [comment]
@robertmain how would you do that?

**Comment by robertmain** [comment]
Remove the PDFs, check the HTML into source control instead. Not a great
idea to have compiled static assets in source control - they get stale very
quickly. Let people compile their own from the HTML. If you need compiled
versions somewhere setup CI to compile them for you nightly and whack them
on Amazon S3 or some such. Happy to answer questions in any of this...
