### ISSUE TITLE
"We are all only temporarily not disabled" - isn't quite true

### ISSUE THREAD

**Issue by accessiblewebuk** [UKHomeOffice/posters#87]
Most people are only temporarily not disabled, but not everyone. People born with a permanent disability do not fit the definition of "all" in this statement.

Not sure how to word it better "Most people are only temporarily not disabled" doesn't quite work and the use of a negative seems easy to misunderstand. However the use of a negative does help provide emphasis for the important message.

**Comment by jbuller** [comment]
Thanks for the feedback. We acknowledge its not ideal from a plain English angle but in it is intended to make you stop and think. It has had a great impact on many people so I wanted to use it. We provide the 'Everyone has abilities and limits to those abilities' poster as an alternative for those who don't like it.

What you say is true under the medical model of disability. However as an example, if I as a person who has had a visually impairment since birth, I am doing nothing but listening to the radio, then at that moment under the social model: I am not being disabled. It is important to acknowledge issues such as chronic pain and other severe cognitive conditions however. 

I didn't like the phrase that has been used elsewhere: 'You are only temporarily able' as its not inclusive of disabled people. I hope that this one is more inclusive, if not perfect.

**Comment by Ryuno-Ki** [comment]
Here's what [Raul Krauthausen](https://raul.de/) (founder of a German association Sozialhelden e.V. and [wheelmap](https://wheelmap.org/map)) [uses to say](https://raul.de/leben-mit-behinderung/vorurteile-zum-thema-inklusion/):

> Schon als Kind hatte ich viel Kontakt zu Menschen ohne Behinderung. Mich hat immer inspiriert, wie viel Lebensfreude sie ausstrahlen und wie gut sie ihr Leben meistern. Seitdem ist es für mich ganz normal, dass es auch Nichtbehinderte gibt.

Translated into English (errors are mine)

> I had much contact to humans without disabilities as child. I was always inspired how much joie de vivre they broadcasted and how well they mastered their life. Since then it is normal to me that there are non-disabled persons.

You can read more about [Wheelmap.org](https://en.wikipedia.org/wiki/Wheelmap.org) and [Raul](https://en.wikipedia.org/wiki/Raul_Krauthausen) on Wikipedia.
I like the tone of it.
